"""updated

Revision ID: 29b40479eb26
Revises: 5960198e47b8
Create Date: 2025-01-09 17:12:31.599631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b40479eb26'
down_revision: Union[str, None] = '5960198e47b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('name', sa.String(), nullable=True))
    op.add_column('restaurant', sa.Column('full_adress', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'full_adress')
    op.drop_column('restaurant', 'name')
    # ### end Alembic commands ###
