"""updated

Revision ID: 326618a45fb9
Revises: aac83f3ac440
Create Date: 2025-01-09 17:11:35.538837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326618a45fb9'
down_revision: Union[str, None] = 'aac83f3ac440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('location', 'pidr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('pidr', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('location', 'name')
    # ### end Alembic commands ###
